from pyspark.sql import DataFrame
from pyspark.sql.window import Window
import pyspark.sql.functions as SF
from logging import Logger

def sales_and_revenues(orders_dataframe: DataFrame
                       ) -> tuple[DataFrame, float]:
    """ Sales analysis over time 
    :param orders_dataframe: Order's DataFrame
    :return: Processed DataFrame and Total System Revenue"""
        
    window_day_rank = Window.orderBy(SF.col("daily_revenue").desc())
    window_t_a_change = Window.orderBy(SF.col("order_day"))

    total_system_revenue = (orders_dataframe
                            .agg(SF.sum("total_amount").alias("total_system_revenue"))
                            ).collect()[0][0]
        
    gold_sales_and_revenues = (orders_dataframe
                            .withColumn("order_day", SF.to_date(SF.col("order_date")))
                            .groupBy("order_day")
                            .agg(SF.round(SF.sum("total_amount"), 2).alias("daily_revenue"),
                                 SF.round(SF.avg("total_amount"), 2).alias("avg_total_amount"),
                                 SF.count("order_id").alias("order_count"))
                            .withColumn("revenue_ranking", SF.row_number().over(window_day_rank))
                            .withColumn("is_in_top_5", SF.when(SF.col("revenue_ranking") <= 5, True)
                                                       .otherwise(False))
                            .withColumn("prev_day", SF.lag("avg_total_amount").over(window_t_a_change))
                            .withColumn("avg_total_amount_change", SF.round(SF.col("avg_total_amount") - SF.col("prev_day"), 2))
                            .withColumn("pct_change_rate", SF.round(SF.col("avg_total_amount_change") / SF.col("prev_day") * 100, 2))
                            .drop("prev_day")
                            )
   
    return gold_sales_and_revenues, total_system_revenue

def geography(orders_dataframe: DataFrame, 
              users_dataframe: DataFrame, 
              total_system_revenue: float,
              logger: Logger
              ) -> tuple[DataFrame, float]:
    """ Geographic sales analysis 
    :param orders_dataframe: Orders DataFrame
    :param users_dataframe: Users DataFrame
    :total_system_revenue: Total number of orders
    :return: Processed DataFrame and percentage of revenue generated by the top 10% of users"""

    window_rev_per_city_ranking = Window.orderBy(SF.col("revenue_per_city").desc())
    window_user_count_ranking = Window.orderBy(SF.col("users_count").desc())
    window_rev_per_user_ranking = Window.orderBy(SF.col("revenue_per_user").desc())


    """ Indirect DataFrame """
    sum_per_user_dataframe = (orders_dataframe
                .groupBy("user_id")
                .agg(SF.round(SF.sum("total_amount"), 2).alias("revenue_per_user"))
                )
        
    """ Top 10% of users """
    all_users_count = sum_per_user_dataframe.count()

    if all_users_count < 10:
        share_in_total_revenue = 0.0
        logger.info(f"Too few users to calculate the percentage share.")

    else:
        top_10_pct_users_count = int(0.1 * all_users_count)
        top_10_pct_users_revenue = (sum_per_user_dataframe
                            .withColumn("amount_row_number", SF.row_number().over(window_rev_per_user_ranking))
                            .filter(SF.col("amount_row_number") <= top_10_pct_users_count)
                            .agg(SF.sum("revenue_per_user").alias("top_10_pct_users_revenue"))
                            ).collect()[0][0]

        share_in_total_revenue = round(top_10_pct_users_revenue / total_system_revenue * 100, 2)

    gold_geography = (sum_per_user_dataframe.alias("o")
                .join(other = users_dataframe.alias("u"), on = "user_id", how = "inner")
                .groupBy("u.city")
                .agg(SF.round(SF.sum("o.revenue_per_user"), 2).alias("revenue_per_city"),
                       SF.count("u.user_id").alias("users_count"),
                       SF.round(SF.avg("o.revenue_per_user"), 2).alias("avg_per_user")
                       )
                .withColumn("revenue_per_city_ranking", SF.row_number().over(window_rev_per_city_ranking))
                .withColumn("users_count_ranking", SF.row_number().over(window_user_count_ranking))
                )

    return gold_geography, share_in_total_revenue

def customer_metrics(orders_dataframe: DataFrame) -> tuple[DataFrame, int, float]:  
    """ Customers analysis 
    :param orders_dataframe: Orders DataFrame
    :return: Processed DataFrame, Amount of active users, Average number of orders per user"""

    gold_customer_metrics = (orders_dataframe
                        .groupBy("user_id")
                        .agg(SF.round(SF.sum("total_amount"), 2).alias("summed_amount"),
                            SF.count("order_id").alias("orders_count"))
                        .withColumn("spent_segment", SF.when(SF.col("summed_amount") > 5000, "high")
                                    .when(SF.col("summed_amount") > 2000, "medium")
                                    .otherwise("low"))
                        .withColumn("more_than_1_order", SF.when(SF.col("orders_count") > 1, True)
                                    .otherwise(False))    
                        )

    active_users_count = (orders_dataframe
                            .agg(SF.count_distinct("user_id").alias("active_users_count"))
                            ).collect()[0][0]

    avg_orders_count_per_user = (gold_customer_metrics
                                    .agg(SF.round(SF.avg("orders_count"), 2).alias("avg_orders_count"))
                                    ).collect()[0][0]
        
    return gold_customer_metrics, active_users_count, avg_orders_count_per_user

def products(order_items_dataframe: DataFrame, 
             users_dataframe: DataFrame
             ) -> tuple[DataFrame, DataFrame]:
    """ Products analysis
    :param order_items_dataframe: Order Items DataFrame
    :param users_dataframe: Users DataFrame
    :return: Processed DataFrame, DataFrame with top products per city"""
    

    window_top_sold_count = Window.orderBy(SF.col("sold_count").desc())
    window_top_revenue = Window.orderBy(SF.col("summary_revenue").desc())
    window_per_city = Window.partitionBy("city").orderBy(SF.col("ordered_quantity").desc())

    products_gold = (order_items_dataframe
                            .groupBy("product_id")
                            .agg(SF.sum("quantity").alias("sold_count"),
                                 SF.round(SF.sum("item_total"), 2).alias("summary_revenue"))
                            .withColumn("sold_count_ranking", SF.row_number().over(window_top_sold_count))
                            .withColumn("top_revenue_ranking", SF.row_number().over(window_top_revenue))
                            )
    
    top_products_per_city = (order_items_dataframe.alias("o")
                                .join(other = users_dataframe.alias("u"), on = "user_id", how = "inner")
                                .select("o.product_id", "o.quantity", "u.city")
                                .groupBy("product_id", "city")
                                .agg(SF.sum("o.quantity").alias("ordered_quantity"))
                                .withColumn("product_per_city_ranking", SF.row_number().over(window_per_city))
                                .filter(SF.col("product_per_city_ranking") <= 10)
                                )
        
    return products_gold, top_products_per_city

def orders(orders_dataframe: DataFrame, 
           order_items_dataframe: DataFrame,
           logger: Logger
           ) -> tuple[DataFrame, float]:
    """ Orders Analysis
    :param orders_dataframe: Orders DataFrame
    :param order_items_dataframe: Order Items DataFrame
    :return: Processed DataFrame, Percentage of orders with more than one item """


    big_orders_count = (order_items_dataframe
                        .groupBy("order_id")
                        .agg(SF.count_distinct("product_id").alias("products_count"))
                        .filter(SF.col("products_count") > 1)
                        ).count()
        
    all_orders_count = orders_dataframe.count()

    if all_orders_count > 0:
        big_orders_share = round(big_orders_count / all_orders_count * 100, 2)
    else:
        big_orders_share = 0.0
        logger.info(f"Too few users to calculate the percentage share.")


    orders_gold = (orders_dataframe
                        .select("order_id", "total_amount")
                        .withColumn("bucket", SF.when(SF.col("total_amount") < 50, "very_low")
                                    .when(SF.col("total_amount") < 150, "low")
                                    .when(SF.col("total_amount") < 300, "medium_low")
                                    .when(SF.col("total_amount") < 600, "medium")
                                    .when(SF.col("total_amount") < 1000, "medium_high")
                                    .when(SF.col("total_amount") < 2000, "high")
                                    .otherwise("very_high")
                                    )
                        )
        
    return orders_gold, big_orders_share

def customers_loyalty(orders_dataframe: DataFrame
                      ) -> DataFrame:

    """ Customer's loyalty analysis
    :param orders_dataframe: Orders DataFrame
    :return: Processed DataFrame"""
    

    window_users_ordered = Window.partitionBy("user_id").orderBy(SF.col("order_date"))
    window_users = Window.partitionBy("user_id")
    window_ranking = Window.orderBy(SF.col("orders_count").desc(), SF.col("avg_interval"))

    gold_customers_loyalty = (orders_dataframe
                                .select("user_id", "order_id", "order_date", "total_amount")
                                .withColumn("orders_count", SF.count("order_id").over(window_users))
                                .withColumn("user_total_amount", SF.round(SF.sum("total_amount").over(window_users), 2))
                                .withColumn("prev_order_date", SF.lag("order_date").over(window_users_ordered))
                                .withColumn("orders_interval", SF.col("order_date") - SF.col("prev_order_date"))
                                .withColumn("avg_interval", SF.avg("orders_interval").over(window_users))
                                .withColumn("loyalty_ranking", SF.dense_rank().over(window_ranking))
                                )
        
    return gold_customers_loyalty